// src-fe/src/views/find.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onBeforeUnmount } from 'vue'
import { invoke } from '@tauri-apps/api/core'
import { listen } from '@tauri-apps/api/event'
import { getFirstTableData } from '@/utilities'
import type { MdastNode } from '@/interface/ast'

const tableData = ref<Record<string, string | undefined>[]>([])
const errorMessage = ref<string>('')
const searchQuery = ref<string>('')
const totalForCell1 = ref({ total: 0, count: 0 })
let unlistenSelectedChange: (() => void) | undefined

const clearTableState = () => {
  tableData.value = []
  errorMessage.value = ''
  totalForCell1.value = { total: 0, count: 0 }
}

const parseMd = async () => {
  try {
    errorMessage.value = ''
    const temp = await invoke<string>('get_markdown_ast')
    const ast: MdastNode = JSON.parse(temp)
    const firstTableData = getFirstTableData(ast)
    tableData.value = firstTableData
  } catch (error) {
    tableData.value = []
    totalForCell1.value = { total: 0, count: 0 }
    if (error instanceof Error) {
      errorMessage.value = '解析失败: ' + error.message
    } else {
      errorMessage.value = '解析失败: 未知错误'
    }
    console.log('parseMd error:', error)
  }
}

const refreshFromSelection = async (selectedFilePath?: string) => {
  if (selectedFilePath !== undefined && !selectedFilePath) {
    clearTableState()
    return
  }

  try {
    const currentSelectedFile = selectedFilePath ?? (await invoke<string>('get_selected_file'))
    if (!currentSelectedFile) {
      clearTableState()
      return
    }
  } catch (error) {
    clearTableState()
    if (error instanceof Error) {
      errorMessage.value = '解析失败: ' + error.message
    } else {
      errorMessage.value = '解析失败: 未知错误'
    }
    return
  }

  await parseMd()
}

const columns = [
  { title: '#', dataKey: 'index', width: 50 },
  { title: 'Column 1', dataKey: 'cell-0', width: 150 },
  { title: 'Column 2', dataKey: 'cell-1', width: 150 },
  { title: 'Column 3', dataKey: 'cell-2', width: 150 },
  { title: 'Column 4', dataKey: 'cell-3', width: '100%' }
]

const filteredData = computed<any[]>(() => {
  if (!searchQuery.value) {
    return tableData.value.map((row, index) => ({ index: index + 1, ...row }))
  }
  return tableData.value
    .filter((row) =>
      Object.values(row).some(
        (val) => val && val.toLowerCase().includes(searchQuery.value.toLowerCase())
      )
    )
    .map((row, index) => ({ index: index + 1, ...row })) // 添加索引
})

watch(searchQuery, (newQuery) => {
  if (newQuery && newQuery.trim().length > 0) {
    let total = 0
    let count = 0
    filteredData.value.forEach((row) => {
      const value = parseFloat(row['cell-1'] || '0')
      if (!isNaN(value)) {
        // 确保是有效的数字
        total += value
        count++
      }
    })
    totalForCell1.value = { total, count }
  } else {
    totalForCell1.value = { total: 0, count: 0 }
  }
})

onMounted(async () => {
  unlistenSelectedChange = await listen<string>('selected-change', async (event) => {
    await refreshFromSelection(event.payload)
  })
  await refreshFromSelection()
})

onBeforeUnmount(() => {
  unlistenSelectedChange?.()
})
</script>

<template>
  <el-card
    style="height: 100%"
    shadow="never"
    :body-style="{ height: 'calc(100% - 80px)', padding: '0 20px 0 20px' }"
  >
    <template #header>
      <div style="display: flex; justify-content: space-between; column-gap: 8px">
        <el-input v-model="searchQuery" clearable style="width: 300px" />
        <div v-if="searchQuery && searchQuery.length > 0" style="justify-self: start">
          <el-space>
            <span>{{ totalForCell1.total }}</span>
            <span>Count of Entries: {{ totalForCell1.count }}</span>
          </el-space>
        </div>
        <el-button @click="parseMd" type="primary">解析</el-button>
      </div>
    </template>
    <div v-if="errorMessage">{{ errorMessage }}</div>
    <div style="height: 100%; width: 100%">
      <el-auto-resizer>
        <template #default="{ height, width }">
          <el-table-v2 :columns="columns" :data="filteredData" :height="height" :width="width" />
        </template>
      </el-auto-resizer>
    </div>
  </el-card>
</template>

// ui-angular/src/app/find/find.ts
import { TableModule } from 'primeng/table';
import { FormsModule } from '@angular/forms';
import { invoke } from '@tauri-apps/api/core';
import { FilterMatchMode } from 'primeng/api';
import { ButtonModule } from 'primeng/button';
import { listen } from '@tauri-apps/api/event';
import { ToolbarModule } from 'primeng/toolbar';
import { MessageModule } from 'primeng/message';
import { Component, OnDestroy, OnInit, computed, signal } from '@angular/core';
import { ClearableInputText } from './clearable-input-text/clearable-input-text';
import { getErrorMessage, getFirstTableData, TableDataRow } from '../../utils';
import type { MdastNode } from '../../types/ast';

type FindColumnField = 'index' | 'cell-0' | 'cell-1' | 'cell-2' | 'cell-3';

type FindTableRow = Record<string, string | number | undefined> & {
  index: number;
};

type TextFilter = {
  value: string | null;
  matchMode: string;
};

type FindTableFilters = Record<FindColumnField | 'global', TextFilter>;

type FindTableTotals = {
  total: number;
  count: number;
};

interface FindColumn {
  field: FindColumnField;
  header: string;
  className: string;
}

@Component({
  selector: 'app-find',
  imports: [
    FormsModule,
    ButtonModule,
    MessageModule,
    TableModule,
    ToolbarModule,
    ClearableInputText,
  ],
  templateUrl: './find.html',
})
export default class Find implements OnInit, OnDestroy {
  private unlistenSelectedChange?: () => void;

  protected readonly globalFilterFields: FindColumnField[] = [
    'index',
    'cell-0',
    'cell-1',
    'cell-2',
    'cell-3',
  ];

  protected readonly columns: FindColumn[] = [
    { field: 'index', header: '#', className: 'min-w-37.5 w-37.5' },
    { field: 'cell-0', header: 'Column 1', className: 'min-w-37.5 w-37.5' },
    { field: 'cell-1', header: 'Column 2', className: 'min-w-37.5 w-37.5' },
    { field: 'cell-2', header: 'Column 3', className: 'min-w-37.5 w-37.5' },
    { field: 'cell-3', header: 'Column 4', className: 'whitespace-nowrap' },
  ];

  protected readonly virtualScrollerOptions = { itemSize: 44 };
  protected readonly tablePassThrough = { tableContainer: 'h-full' };
  protected readonly filters = signal<FindTableFilters>({
    global: { value: null, matchMode: FilterMatchMode.CONTAINS },
    index: { value: null, matchMode: FilterMatchMode.CONTAINS },
    'cell-0': { value: null, matchMode: FilterMatchMode.CONTAINS },
    'cell-1': { value: null, matchMode: FilterMatchMode.CONTAINS },
    'cell-2': { value: null, matchMode: FilterMatchMode.CONTAINS },
    'cell-3': { value: null, matchMode: FilterMatchMode.CONTAINS },
  });

  protected readonly tableData = signal<TableDataRow[]>([]);
  protected readonly filteredRows = signal<FindTableRow[]>([]);
  protected readonly errorMessage = signal('');
  protected readonly isLoading = signal(false);

  protected readonly tableRows = computed<FindTableRow[]>(() => {
    return this.tableData().map((row, index) => ({ index: index + 1, ...row }));
  });

  protected readonly hasActiveFilter = computed(() => {
    return Object.values(this.filters()).some((filter) => Boolean(filter.value?.trim()));
  });

  protected readonly totalForCell1 = computed<FindTableTotals>(() => {
    if (!this.hasActiveFilter()) {
      return { total: 0, count: 0 };
    }

    return this.filteredRows().reduce(
      (result, row) => {
        const value = parseFloat(String(row['cell-1'] ?? '0'));
        if (!Number.isNaN(value)) {
          result.total += value;
          result.count += 1;
        }

        return result;
      },
      { total: 0, count: 0 },
    );
  });

  async ngOnInit() {
    this.unlistenSelectedChange = await listen<string>('selected-change', async (event) => {
      await this.refreshFromSelection(event.payload);
    });
    await this.refreshFromSelection();
  }

  ngOnDestroy() {
    this.unlistenSelectedChange?.();
  }

  protected async parseMd() {
    try {
      this.isLoading.set(true);
      this.errorMessage.set('');
      const markdownAst = await invoke<string>('get_markdown_ast');
      const ast = JSON.parse(markdownAst) as MdastNode;
      this.tableData.set(getFirstTableData(ast));
      this.applyFilters();
    } catch (error) {
      this.tableData.set([]);
      this.filteredRows.set([]);
      this.errorMessage.set('解析失败: ' + getErrorMessage(error));
    } finally {
      this.isLoading.set(false);
    }
  }

  protected setFilter(field: keyof FindTableFilters, value: string | null) {
    this.filters.update((filters) => ({
      ...filters,
      [field]: {
        ...filters[field],
        value,
      },
    }));
    this.applyFilters();
  }

  protected trackByIndex(_: number, row: FindTableRow) {
    return row.index;
  }

  private clearTableState() {
    this.tableData.set([]);
    this.filteredRows.set([]);
    this.errorMessage.set('');
  }

  private async refreshFromSelection(selectedFilePath?: string) {
    if (selectedFilePath !== undefined && !selectedFilePath) {
      this.clearTableState();
      return;
    }

    try {
      const currentSelectedFile = selectedFilePath ?? (await invoke<string>('get_selected_file'));
      if (!currentSelectedFile) {
        this.clearTableState();
        return;
      }
    } catch (error) {
      this.clearTableState();
      this.errorMessage.set('解析失败: ' + getErrorMessage(error));
      return;
    }

    await this.parseMd();
  }

  private applyFilters() {
    const rows = this.tableRows();
    this.filteredRows.set(rows.filter((row) => this.matchesFilters(row)));
  }

  private matchesFilters(row: FindTableRow) {
    const filters = this.filters();
    const globalFilter = this.normalizeFilterValue(filters.global.value);
    if (
      globalFilter &&
      !this.globalFilterFields.some((field) => this.matchesTextFilter(row[field], globalFilter))
    ) {
      return false;
    }

    return this.columns.every((column) => {
      const filterValue = this.normalizeFilterValue(filters[column.field].value);
      return !filterValue || this.matchesTextFilter(row[column.field], filterValue);
    });
  }

  private normalizeFilterValue(value: string | null) {
    return value?.trim().toLocaleLowerCase() ?? '';
  }

  private matchesTextFilter(value: string | number | undefined, filterValue: string) {
    if (value === undefined || value === null) {
      return false;
    }

    return String(value).toLocaleLowerCase().includes(filterValue);
  }
}
